config/routes.rb
Rails.application.routes.draw do
  get 'reservers/index'
  resources :greenhouses do
    collection do
      get 'search'
    end
  end
  root 'homes#top'
  resource :user, only: [:new, :create, :show]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  resources :users, only: [:edit, :update]
  patch 'user', to: "users#update"
  resources :reservers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/greenhouse.rb
class Greenhouse < ApplicationRecord
has_one_attached :image
belongs_to :user
has_one :reserver

validates :name, presence: true
validates :introduction, presence: true
validates :price, presence: true
validates :address, presence: true
validates :image, presence: true
end

app/models/reserver.rb
class Reserver < ApplicationRecord
  belongs_to :user
  belongs_to :greenhouse
  
  validates :start, presence: true
  validates :end, presence: true
  validates :number, presence: true
  
   def total_fee
    (@reservers.end - @reservers.start).to_i* @greenhouses.price * @reservers.number
   end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :image
  has_many :reservers
  has_many :greenhouses
  
  validates :nickname, presence: true
  validates :email, uniqueness: true, presence: true
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  def login?
    if current_user.nil?
      redirect_to login_path, alert: "ログインしてください"
    end
  end
  
  def already_login?
    unless current_user.nil?
      redirect_to user_path, notice: "既にログイン済みです"
    end
  end
  
  def current_user
    if session[:user_id]
      current_user ||= User.find(session[:user_id])
    end
  end
end

app/controllers/greenhouses_controller.rb
class GreenhousesController < ApplicationController
  before_action :set_greenhouse, only: %i[ show edit update destroy ]
  before_action :set_q, only: [:index, :search]
  # GET /greenhouses or /greenhouses.json
  def index
    @greenhouses = Greenhouse.all
  end

  # GET /greenhouses/1 or /greenhouses/1.json
  def show
  end

  # GET /greenhouses/new
  def new
    @greenhouse = Greenhouse.new
  end

  # GET /greenhouses/1/edit
  def edit
  end

  # POST /greenhouses or /greenhouses.json
  def create
    @greenhouse = Greenhouse.new(greenhouse_params)
    @greenhouse.user_id = current_user.id
    respond_to do |format|
      if @greenhouse.save
        format.html { redirect_to @greenhouse, notice: "新しく登録しました" }
        format.json { render :show, status: :created, location: @greenhouse }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @greenhouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /greenhouses/1 or /greenhouses/1.json
  def update
    respond_to do |format|
      if @greenhouse.update(greenhouse_params)
        format.html { redirect_to @greenhouse, notice: "更新しました" }
        format.json { render :show, status: :ok, location: @greenhouse }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @greenhouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /greenhouses/1 or /greenhouses/1.json
  def destroy
    @greenhouse.destroy
    respond_to do |format|
      format.html { redirect_to greenhouses_url, notice: "削除しました" }
      format.json { head :no_content }
    end
  end
  
  def search
    @results = @q.result
  end
  
  def set_q
    @q = Greenhouse.ransack(params[:q])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_greenhouse
      @greenhouse = Greenhouse.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def greenhouse_params
      params.require(:greenhouse).permit(:name, :introduction, :price, :address, :image)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/reservers_controller.rb
class ReserversController < ApplicationController
  def index
    @reservers = Reserver.all
  end
  
  def new
    @reserver = Reserver.new
    @reserver.greenhouse = 
    @greenhouse = Greenhouse.find(params[:format])
  end
  
  def create
   @reserver = Reserver.new(params.require(:reserver).permit(:start, :end, :number, :total, :user_id, :greenhouse_id))
        if @reserver.save
          flash[:notice] = "新規予約をしました"
          redirect_to action: :index
        else
         @greenhouse = Reserver.find(params[:reserver][:greenhouse_id])
         render :new
        end
  end

  def show
    @reserver = Reserver.find(params[:id])
  end
  
  def edit
    @reserver = Reserver.find(params[:id])
  end
  
  def update
    @reserver = Reserver.find(params[:id])
        if @reserver.update(params.require(:reserver).permit(:start, :end, :number, :total, :user_id, :greenhouse_id))
          flash[:notice] = "投稿を更新しました"
          redirect_to :reservers
        else
          render "edit"
        end
  end
  
  def destroy
    @reserver = Reserver.find(params[:id])
        @reserver.destroy
        flash[:notice] = "投稿を削除しました"
        redirect_to :reservers
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_login?, except: :destroy
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path, notice: "ログインしました"
    else
      flash.now[:alert] = "メールアドレスまたはパスワードが間違っています。"
      render :new
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "ログアウトしました"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_login?, only: [:new, :create]
  before_action :login?, only: :show
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path, notice: "ログインに成功しました"
    else
      render :new
    end
  end

  def show
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    if current_user.update(user_params)
    redirect_to user_path, notice: "編集しました"
    else
    render :edit
    end
  end
  
   private
  def user_params
    params.require(:user).permit(:nickname, :image, :introduction, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greenhouses_helper.rb
module GreenhousesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reservers_helper.rb
module ReserversHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/greenhouses/_form.html.erb
<%= form_with(model: greenhouse) do |form| %>
  <div class="field">
    <%= form.label :ルーム名 %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :紹介 %>
    <%= form.text_area :introduction %>
  </div>

  <div class="field">
    <%= form.label :料金 %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :住所 %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :イメージ %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/greenhouses/edit.html.erb
<h1>ルーム編集</h1>

<%= render 'form', greenhouse: @greenhouse %>

<%= link_to '詳細', @greenhouse %> |
<%= link_to '戻る', greenhouses_path %>

app/views/greenhouses/index.html.erb
<div class ="new_header">
              <%= search_form_for @q, url: search_greenhouses_path do |f| %>
              <%= f.search_field :name_or_address_or_introduction_or_price_cont, placeholder:"キーワード" %>
              <br>
              <%= f.submit '検索' %>
              <% end %>
              
              <%= search_form_for @q, url: search_greenhouses_path do |f| %>
              <%= f.search_field :address_cont, placeholder:"エリア" %>
              <br>
              <%= f.submit '検索' %>
              <% end %>
              </div>

<div class ="main_body">
  <body>
    <div class = "free_sarch">
    <p>
    Potepan Shareで<br>まだ体験したことのない旅をしよう
   </p>
   
 <%= search_form_for @q, url: search_greenhouses_path do |f| %>
  <%= f.search_field :name_or_address_or_introduction_or_price_cont, placeholder:"エリア" %>

  <div class = "search_button" ><%= f.submit "探す" %></div>
<% end %>
   </div>
  </body>
</div>

<div class ="sub_body">
  <body>
    <h1>おすすめのエリア</h1>
    <div class ="contain">
      <div class ="individual_items">
        <span>東京</span>
      <a href ="https://c9ea7a77300e4c528e026de45c8006a6.vfs.cloud9.us-east-2.amazonaws.com/greenhouses/search?q%5Bname_or_address_or_introduction_or_price_cont%5D=%E6%9D%B1%E4%BA%AC&commit=%E6%8E%A2%E3%81%99">
      <img src ="https://www.jukushin.com/wp-content/uploads/2012/05/350a09baa9a90589dbce421039fe274a.jpg" alt ="東京について">
      </a>
      </div>
      <div class ="individual_items">
        <span>大阪</span>
      <a href ="https://c9ea7a77300e4c528e026de45c8006a6.vfs.cloud9.us-east-2.amazonaws.com/greenhouses/search?q%5Bname_or_address_or_introduction_or_price_cont%5D=%E5%A4%A7%E9%98%AA&commit=%E6%8E%A2%E3%81%99">
      <img src ="https://gahag.net/img/201605/25s/gahag-0089691144-1.jpg" alt ="大阪について">
      </a>
      </div>
      <div class ="individual_items">
        <span>京都</span>
      <a href ="https://c9ea7a77300e4c528e026de45c8006a6.vfs.cloud9.us-east-2.amazonaws.com/greenhouses/search?q%5Bname_or_address_or_introduction_or_price_cont%5D=%E4%BA%AC%E9%83%BD&commit=%E6%8E%A2%E3%81%99">
      <img src ="https://publicdomainq.net/images/201705/06s/publicdomainq-0008766fuw.jpg" alt ="京都について">
      </a>
      </div>
      <div class ="individual_items">
        <span>札幌</span>
      <a href ="https://c9ea7a77300e4c528e026de45c8006a6.vfs.cloud9.us-east-2.amazonaws.com/greenhouses/search?q%5Bname_or_address_or_introduction_or_price_cont%5D=%E6%9C%AD%E5%B9%8C&commit=%E6%8E%A2%E3%81%99">
      <img src ="https://www.photock.jp/photo/middle/photo0000-1892.jpg" alt ="札幌について">
      </a>
      </div>
    </div>
  </body>
</div>

app/views/greenhouses/new.html.erb
<h1>新規登録</h1>

<%= render "shared/error", obj: @greenhouse %>

<%= render 'form', greenhouse: @greenhouse %>

<%= link_to '戻る', greenhouses_path %>

app/views/greenhouses/search.html.erb
<div class ="room_table">
<h1>検索結果</h1>
<table>
  <thead>
    <tr>
      <th>ルーム名</th>
      <th>紹介</th>
      <th>料金</th>
      <th>住所</th>
      <th>イメージ</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |greenhouse| %>
      <tr>
        <td><%= greenhouse.name %></td>
        <td><%= greenhouse.introduction %></td>
        <td><%= greenhouse.price %></td>
        <td><%= greenhouse.address %></td>
        <td><%= image_tag greenhouse.image %></td>
        <td><%= link_to '詳細', greenhouse %></td>
        <td><%= link_to '更新', edit_greenhouse_path(greenhouse) %></td>
        <td><%= link_to '削除', greenhouse, method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
        <td><%= link_to '予約する', new_reserver_path(greenhouse) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'トップ', greenhouses_path %>
</div>

app/views/greenhouses/show.html.erb
<div class ="room_details">
<p id="notice"><%= notice %></p>

<p>
  <strong>ルーム名:</strong>
  <%= @greenhouse.name %>
</p>

<p>
  <strong>紹介:</strong>
  <%= @greenhouse.introduction %>
</p>

<p>
  <strong>料金:</strong>
  <%= @greenhouse.price %>
</p>

<p>
  <strong>住所:</strong>
  <%= @greenhouse.address %>
</p>

<p class ="room_img">
  <strong class = "room_title">イメージ:</strong>
  <% if @greenhouse.image.attached? %>
  <%= image_tag @greenhouse.image %>
  <% end %>
</p>

<%= link_to '更新', edit_greenhouse_path(@greenhouse) %> |
<%= link_to '戻る', greenhouses_path %>
</div>

app/views/homes/top.html.erb
<h1>こんにちは！</h1>

<%= link_to "新規作成", new_user_path %>
<%= link_to "ログイン", login_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Room</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <%= alert %>
    <div class = "container">
      <header class ="new_header">
          <a href="https://c9ea7a77300e4c528e026de45c8006a6.vfs.cloud9.us-east-2.amazonaws.com/greenhouses">
            <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png" alt="ロゴ">
            </a>
            <div class ="menu_bar">
            <%= link_to 'ルーム新規登録', new_greenhouse_path %>
            <%= link_to "ルーム予約一覧", reservers_path %>
            <%= link_to "ログアウト", logout_path, method: :delete %>
            </div>
        </header>
    <%= yield %>
    <footer class ="new_footer">
          <p class = "footer_text">© 2020 POTEPAN.INC.</p>
        </div>
    </div>
  </body>
</html>

app/views/reservers/edit.html.erb
<h3>予約編集</h3>
 
    <%= form_for @reserver do |f| %>
      <table>
        <tr>
           <th><%= f.label :開始日 %></th>
           <td><%= f.date_field :start, class:"start-content" %></td>
         </tr>
         
         <tr>
           <th><%= f.label :終了日 %></th>
           <td><%= f.date_field :end, class:"end-content" %></td>
         </tr>
         
         <tr>
           <th><%= f.label :人数 %></th>
           <td><%= f.number_field :number, class:"number-content" %></td>
         </tr>
      </table>
      <div>
        <ul>
          <li><%= f.submit "編集を完了する" %></li>
          <li><%= link_to "予約一覧に戻る", :reservers %></li>
        </ul>
      </div>
    <% end %>

app/views/reservers/index.html.erb
 <h3>予約一覧</h3>
  
     <table>
       <thead>
         <tr>
           <th>ルーム名</th>
           <th>イメージ</th>
           <th>開始日</th>
           <th>終了日</th>
           <th>人数</th>
           <th>合計金額</th>
           <th>参照</th>
           <th>編集</th>
           <th>削除</th>
         </tr>
       </thead>
       
       <tbody>
         <% @reservers.each do |reserver| %>
           <tr>
             <td><%= reserver.greenhouse.name %></td>
             <td class = "room_sample"><%= image_tag reserver.greenhouse.image %></td>
             <td><%= reserver.start %></td>
             <td><%= reserver.end %></td>
             <td><%= reserver.number %></td>
             <td><%= (reserver.end - reserver.start).to_i* reserver.greenhouse.price * reserver.number %>円</td>
             <td>
              <%= link_to "参照", reserver %>
            </td>
            <td>
              <%= link_to "編集", [:edit, reserver] %>
            </td>
            <td>
              <%= link_to "削除", reserver, method: :delete, data: { confirm: "本当に削除しますか？" } %>
            </td>
           </tr>
         <% end %>
       </tbody>
     </table>

app/views/reservers/new.html.erb
<h3>新規予約</h3>
  
  <%= render "shared/error", obj: @reserver %>
          
     <%= form_for @reserver do |f| %>
     <%= f.hidden_field :user_id, value: current_user.id %>
     <%= f.hidden_field :greenhouse_id, value: @greenhouse.id %>
     <table class = "reserver_table" >
      <tr>
  <th>サンプルイメージ</th>
  <td class = "room_sample">
   <%= image_tag @reserver.greenhouse.image %>
   </td>
   </tr>
   <tr>
    <th>料金</th>
    <td><%= @reserver.greenhouse.price %>円/日</td>
    </tr>
         <tr>
           <th><%= f.label :開始日 %></th>
           <td><%= f.date_field :start, class:"start-content" %></td>
         </tr>
         
         <tr>
           <th><%= f.label :終了日 %></th>
           <td><%= f.date_field :end, class:"end-content" %></td>
         </tr>
         
         <tr>
           <th><%= f.label :人数 %></th>
           <td><%= f.number_field :number, class:"number-content" %></td>
         </tr>
       </table>
       <div>
         <ul>
           <li><%= f.submit "予約を完了する" %></li>
         </ul>
       </div>
     <% end %>
  
     <div>
       <ul>
         <li><%= link_to "予約一覧に戻る", :reservers %></li>
       </ul>
     </div>

app/views/reservers/show.html.erb
<h3>予約詳細</h3>
 
    <table>
      <tr>
        <th>ルーム名</th>
        <td><%= @reserver.greenhouse.name %></td>
      </tr>
      <tr>
        <th>イメージ</th>
        <td class = "room_sample"><%= image_tag @reserver.greenhouse.image %></td>
      </tr>
      <tr>
        <th>開始日</th>
        <td><%= @reserver.start %></td>
      </tr>
      <tr>
        <th>終了日</th>
        <td><%= @reserver.end %></td>
      </tr>
      <tr>
        <th>人数</th>
        <td><%= @reserver.number %></td>
      </tr>
      <tr>
        <th>合計金額</th>
        <td><%= (@reserver.end - @reserver.start).to_i* @reserver.greenhouse.price * @reserver.number %>円</td>
      </tr>
    </table>
 
    <div>
      <ul>
        <li><%= link_to "予約一覧に戻る", :reservers %></li>
      </ul>
    </div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
      <% obj.errors.full_messages.each do |message| %>
        <ul>
          <li><%= message %></p>
        </ul>
      <% end %>
    <% end %>

app/views/users/edit.html.erb
<h1>ユーザー編集</h1>

<%= form_with model: @user, url: user_path, local: true do |f| %>
<div class ="filed">
  <%= f.label :名前 %><br>
  <%= f.text_field :nickname %>
</div>

<div class ="filed">
  <%= f.label :アイコン %><br>
  <%= f.file_field :image %>
</div>

<div class ="filed">
  <%= f.label :自己紹介 %><br>
  <%= f.text_field :introduction %>
</div>

<div class ="filed">
  <%= f.label :メールアドレス %><br>
  <%= f.text_field :email %>
</div>

<div class ="filed">
  <%= f.label :パスワード %><br>
  <%= f.password_field :password %>
</div>

<div class ="filed">
  <%= f.label :パスワード再入力 %><br>
  <%= f.password_field :password_confirmation %>
</div>

<div>
  <%= f.submit "編集完了" %>
</div>
<% end %>

app/views/users/new.html.erb
<h1>新規登録</h1>

<%= render "shared/error", obj: @user %>

<%= form_with model: @user, url: user_path, local: true do |f| %>
<div class ="filed">
  <%= f.label :名前 %><br>
  <%= f.text_field :nickname %>
</div>

<div class ="filed">
  <%= f.label :メールアドレス %><br>
  <%= f.text_field :email %>
</div>

<div class ="filed">
  <%= f.label :パスワード %><br>
  <%= f.password_field :password %>
</div>

<div class ="filed">
  <%= f.label :パスワード再入力 %><br>
  <%= f.password_field :password_confirmation %>
</div>

<div>
  <%= f.submit "登録" %>
</div>
<%= link_to "ログイン", login_path %>
<% end %>

app/views/users/show.html.erb
<h1>ようこそ！</h1>

<p>あなたは"<strong><%= current_user.email %></strong>"でログインしました</p>
<%= link_to "ログアウト", logout_path, method: :delete %>
<%= link_to "プロフィール編集", edit_user_path(current_user) %>
<%= link_to "potepan shareへ", greenhouses_path %>
<%= link_to "ルーム予約へ", reservers_path %>